apiVersion: apps/v1
kind: Deployment
metadata:
  name: asgbanky-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asgbanky
  template:
    metadata:
      labels:
        app: asgbanky
    spec:
      containers:
      - name: asgbanky
        image: 051370879805.dkr.ecr.us-east-1.amazonaws.com/asg
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: asgbanky
    k8s-app: asgbanky
  name: asgbanky
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: asgbanky
